start-at-login = true

# See https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout tiles horizontal horizontal'
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-shift-h = 'move-mouse monitor-force-center'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-a = 'workspace 1' # Alacritty
alt-b = ['exec-and-forget open /Applications/Google\ Chrome.app', 'workspace 2'] # Browser
alt-s = ['exec-and-forget open /Applications/Slack.app', 'workspace 3'] # Slack
alt-shift-f = ['exec-and-forget open ~', 'workspace F'] # Finder

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-m = 'move-workspace-to-monitor --wrap-around next'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 1' 

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = 'move-node-to-workspace 2' 

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 3' 

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace F'
