return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "p00f/nvim-ts-rainbow",
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  build = ":TSUpdate",
  config = function()
    require("nvim-treesitter.configs").setup({
      auto_install = true,
      ensure_installed = {
        "javascript",
        "typescript",
        "vue",
        "lua",
        "css",
        "bash",
        "json",
        "typescript",
        "dockerfile",
        "html",
        "python",
        "scss",
        "markdown",
        "tsx",
        "cpp",
        "make",
        "cmake",
        "c",
        "yaml",
        "c_sharp",
        "markdown_inline",
      },
      sync_install = false,
      ignore_install = { "" },
      highlight = {
        enable = true,
        disable = { "" },
        additional_vim_regex_highlighting = true,
      },
      indent = { enable = true, disable = { "yaml" } },
      rainbow = {
        enable = true,
        max_file_lines = nil,
      },
      textobjects = {
        move = {
          enable = true,
          set_jumps = true,
          goto_next_start = {
            ["]f"] = "@function.outer",
            ["]b"] = "@parameter.outer",
            ["]d"] = "@block.inner",
            ["]e"] = "@function.inner",
            ["]a"] = "@attribute.inner",
            ["]s"] = "@this_method_call",
            ["]c"] = "@method_object_call",
            ["]o"] = "@object_declaration",
            ["]k"] = "@object_key",
            ["]v"] = "@object_value",
            ["]w"] = "@method_parameter",
          },
          goto_next_end = {
            ["]F"] = "@function.outer",
            ["]B"] = "@parameter.outer",
            ["]D"] = "@block.inner",
            ["]E"] = "@function.inner",
            ["]A"] = "@attribute.inner",
            ["]S"] = "@this_method_call",
            ["]C"] = "@method_object_call",
            ["]O"] = "@object_declaration",
            ["]K"] = "@object_key",
            ["]V"] = "@object_value",
            ["]W"] = "@method_parameter",
          },
          goto_previous_start = {
            ["[f"] = "@function.outer",
            ["[b"] = "@parameter.outer",
            ["[d"] = "@block.inner",
            ["[e"] = "@function.inner",
            ["[a"] = "@attribute.inner",
            ["[s"] = "@this_method_call",
            ["[c"] = "@method_object_call",
            ["[o"] = "@object_declaration",
            ["[k"] = "@object_key",
            ["[v"] = "@object_value",
            ["[w"] = "@method_parameter",
          },
          goto_previous_end = {
            ["[F"] = "@function.outer",
            ["[B"] = "@parameter.outer",
            ["[D"] = "@block.inner",
            ["[E"] = "@function.inner",
            ["[A"] = "@attribute.inner",
            ["[S"] = "@this_method_call",
            ["[C"] = "@method_object_call",
            ["[O"] = "@object_declaration",
            ["[K"] = "@object_key",
            ["[V"] = "@object_value",
            ["[W"] = "@method_parameter",
          },
        },
        select = {
          enable = true,
          lookahead = true,
          keymaps = {
            ["af"] = "@function.outer",
            ["if"] = "@function.inner",
            ["ac"] = "@call.outer",
            ["ic"] = "@call.inner",
            ["aC"] = "@class.outer",
            ["iC"] = "@class.inner",
            ["ib"] = "@parameter.inner",
            ["ab"] = "@parameter.outer",
            ["iB"] = "@block.inner",
            ["aB"] = "@block.outer",
            ["id"] = "@block.inner",
            ["ad"] = "@block.outer",
            ["il"] = "@loop.inner",
            ["al"] = "@loop.outer",
            ["ia"] = "@attribute.inner",
            ["aa"] = "@attribute.outer",
          },
        },
      },
    })
  end,
}
